//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.10 at 08:06:59 AM CET 
//


package com.damek.weather_tieto.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="weathers" type="{http://soap.weather_tieto.damek.com}ArrayOfWeather"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "weathers"
})
@XmlRootElement(name = "getWeatherAllResponse")
public class GetWeatherAllResponse {

    @XmlElement(required = true)
    protected ArrayOfWeather weathers;

    /**
     * Gets the value of the weathers property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfWeather }
     *     
     */
    public ArrayOfWeather getWeathers() {
        return weathers;
    }

    /**
     * Sets the value of the weathers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfWeather }
     *     
     */
    public void setWeathers(ArrayOfWeather value) {
        this.weathers = value;
    }

}
