//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.10 at 08:06:59 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://soap.weather_tieto.damek.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.damek.weather_tieto.soap;
